collections:
  - name: community.general
  - name: redpanda.cluster
    type: galaxy
  - name: ansible.posix
  - name: grafana.grafana
    version: 5.6.0
  - name: prometheus.prometheus

roles:
  - src: geerlingguy.node_exporter
